<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [57]:
# Input 1
A = [[1, 3, 4],
     [2, 5, 7],
     [5, 9, 6 ]]  
B = [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]]

# Input 2
'''
A = [[1, 2],
     [3, 4]]
B = [[1, 2, 3, 4, 5],
     [5, 6, 7, 8, 9]]
'''
# Input 3
'''
A = [[1, 2],
     [3, 4]]
B = [[1, 4],
     [5, 6],
     [7, 8],
     [9, 6]]
'''
def matrix_mul(A, B):
    """
        This function will find the product of two matrices
    """
    # A,B : Matrices to be multiplied
    # check for feasibility of matrix multiplication
    if(len(A[0]) != len(B)):
        return "A*B =Not possible"
    else:
    # multiplication feasible. create a resultant matrix
        result =[]
        for i in range(len(A)):
            lst =[]
            result.append(lst)
            for j in range(len(B[0])):
                lst.append(0)
    # multiply A and B and put the product to result.
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(B)):
                    result[i][j] += A[i][k] * B[k][j] 
        return(result)

 
matrix_mul(A, B)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform


def pick_a_number_from_list(A):
    """
      This function will pick a number from the list A with a probability of its magnitude
    """
    #Compute sum of all elements in the list
    sum = 0;
    for ele in A: sum += ele
    
    # Compute normalized Sum
    normal_sum =[]
    for ele in A:  normal_sum.append(ele/sum)
    
    # Compute cumulative Sum
    cum_sum =[];  tilda =0
    for ele in normal_sum:
        tilda +=ele  
        cum_sum.append(tilda)
    # Generate a uniform random variable
    r = uniform (0.0,1.0)
    for index,num in enumerate(cum_sum):
        if(r<= num):
            return index

def sampling_based_on_magnitude():
    A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]  
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(A[number])

sampling_based_on_magnitude()

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [59]:
import re
# String: it will be the input to your program
def replace_digits(String):
    '''
        This function removes all the non digits and replace the digits with # symbol
    '''   
    digitString = re.sub('\D', "",String)
    replacedString = re.sub('[0-9]','#',digitString)
    return(replacedString) # modified string which is after replacing the # with digits

String = input("Enter the String to be replaced: ")
print (replace_digits(String))

Enter the String to be replaced: 33@11
####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
import math

def display_dash_board(students, marks):
    '''
      This function displays the Students Mark Dashboard
    '''
    student_score =dict(zip(students,marks))
        
    # compute top 5 students
    top_5_students = sorted(student_score.items(), key=lambda x: x[1], reverse=True)[:5]
    print (top_5_students)
    # compute least 5 students
    least_5_students = sorted(student_score.items(), key=lambda x: x[1])[:5]
    print (least_5_students)
    # compute students between 25th and 75th percentile
    percentile_25_75 = list(range(percentile(marks,25), percentile(marks,75)))
    students_within_25_and_75 = {k:v for k,v in student_score.items() if v in percentile_25_75}
    print (sorted(students_within_25_and_75.items(), key=lambda x: x[1]))
        

def percentile(data, perc: int):
    '''
      This function displays the reqiured percentile
      courtesy: https://stackoverflow.com/questions/2374640/how-do-i-calculate-percentiles-with-python-numpy
    '''  
    size = len(data)
    return sorted(data)[int(math.ceil((size * perc) / 100)) - 1]

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
display_dash_board(Students, Marks)


[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
[('student3', 12), ('student4', 14), ('student9', 22), ('student6', 43), ('student1', 45)]
[('student9', 22), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math

# S is list of tuples and P is the point
def closest_points_to_p(S, P):
    '''
     This function finds the cosine distance between each points and returns closest 5 points   
    '''
    dist_dict ={}
    for ele in S:
        #dist_dict[ele] =spatial.distance.cosine (ele,P)
        dotProd = ele[0]*P[0] + ele[1]*P[1]
        lengthProd = (math.sqrt(ele[0]**2+ ele[1]**2)) * (math.sqrt(P[0]**2 + P[1]**2))
        cosine_distance = math.acos(dotProd/lengthProd)
        dist_dict[ele] = cosine_distance
    sorted_dist ={k: v for k, v in sorted(dist_dict.items(), key=lambda item: item[1])}
    return list(sorted_dist.keys())[:5]    

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) 


[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re

def findResultant(points,coeff):
    resultant =[]
    for val in points:
        result = val[0]*coeff[0]+val[1]*coeff[1]+coeff[2]
        if(result == 0): return [] #empty result.Because point is on the line
        elif (result<0): resultant.append('0') #indicates result is negative
        else : resultant.append('1') #indicates result is positive
    return resultant

def i_am_the_one(red,blue,line):
    #Get x,y and intercept values
    result = re.findall(r'[-+]?[\d\.\d]+', line)
    lineCoeff = [float(i) for i in result]
    blue_resultant=[]
    red_resultant = findResultant(red,lineCoeff)
    # No need to check for blue points if red points are on the line.
    if (len(red_resultant) != 0):
        blue_resultant = findResultant(blue,lineCoeff)
    
    if(len(red_resultant) == 0 or len(blue_resultant) == 0):
        return 'NO'
    red_set = set(red_resultant)
    blue_set = set(blue_resultant)
    if(len(red_set) ==1 and len(blue_set) ==1): #set contains either +ve or -ve values(1 or 0)
        if(red_set.intersection(blue_set)): return 'NO' #intersection will tell whether both set has the same value
        else: return 'YES' #No intersection means points are on opposite sides
    else: # set contains both -ve and +ve values 
        return 'NO'
    
Red= [(1,1),(2,1),(3,2),(2,4),(-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) 

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [56]:
def smoothened_list(int_list):
    first=0; last=0; count=0
    for index,num in enumerate(int_list):
        if(index ==0) and (num>0):
            first =num    
        elif (index >0) and (num>0):
            last =num 
            break
        count +=1
    if (last == 0) : result = (first+last)/count; count-=1
    else: result = (first+last)/(count+1)     
    
    lst =[]
    for i in range(1,count+2):
        lst.append(int(result))
    return lst
    
def curve_smoothing(string):
    splitedS= string.split(',')
    int_list = [int(i) if i!='_' else 0 for i in splitedS]
    final_lst =[]
    lst = int_list

    while(True) :
        lst = smoothened_list(lst)
        if(len(final_lst)+len(lst) == len(int_list)):
            final_lst = final_lst +lst
            break;
        length = len(lst)
        lst.extend(int_list[length+len(final_lst):])
        final_lst.extend(lst[ :length-1])
        lst = lst[length-1:]

    return final_lst

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    '''
    This function prints the conditional probability
    '''
    Fdistinct = set()
    Sdict ={}
    for i in A:
        Fdistinct.add(i[0])
        if(i[1] in Sdict.keys()):
            Sdict[i[1]] = Sdict[i[1]] +1
        else:
            Sdict[i[1]] = 1  

    for i in Fdistinct:
        for k,v in Sdict.items():
            count =0
            for ele in A:
                if (ele[0] == i and ele[1]== k): count =count+1  
            print("P(F={}|S=={})= {}/{}".format(i,k,count,v))

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)= 1/4
P(F=F1|S==S2)= 1/3
P(F=F1|S==S3)= 0/3
P(F=F5|S==S1)= 1/4
P(F=F5|S==S2)= 0/3
P(F=F5|S==S3)= 0/3
P(F=F2|S==S1)= 1/4
P(F=F2|S==S2)= 1/3
P(F=F2|S==S3)= 1/3
P(F=F4|S==S1)= 1/4
P(F=F4|S==S2)= 0/3
P(F=F4|S==S3)= 1/3
P(F=F3|S==S1)= 0/4
P(F=F3|S==S2)= 1/3
P(F=F3|S==S3)= 1/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
def string_features(S1, S2):
    S1_list = S1.split() 
    S2_list = S2.split() 
    a =0; b=[]; c=[]
    for ele in S1_list:
        if(ele in S2_list):
            a = a+1
        else:
            b.append(ele)
    c = [ele for ele in S2_list if ele not in S1_list]
    return a,b,c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
import math
def compute_log_loss(A):
    length = len(A)
    log_sum = 0
    for i in A:
        log_sum += i[0]*math.log(i[1],10) + (1-i[0])*math.log(1-i[1],10)
    loss = (-1/len(A)) * log_sum;
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
